#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 18 17:57:21 2024

@author: komal
"""


annex1 = ['Australia',
          'Austria',
          'Belarus',
          'Belgium',
          'Bulgaria',
          'Canada',
          'Croatia',
          'Cyprus',
          'Czech Republic',
          'Denmark',
          'Estonia',
          'European Union',
          'Finland',
          'France',
          'Germany',
          'Greece',
          'Hungary',
          'Iceland',
          'Ireland',
          'Italy',
          'Japan',
          'Latvia',
          'Liechtenstein',
          'Lithuania',
          'Luxembourg',
          'Malta',
          'Monaco',
          'Netherlands',
          'New Zealand',
          'Norway',
          'Poland',
          'Portugal',
          'Romania',
          'Russia',
          'Slovakia',
          'Slovenia',
          'Spain',
          'Sweden',
          'Switzerland',
          'Turkey',
          'Ukraine',
          'United Kingdom',
          'United States']

non_annex1 = ['Afghanistan',
              'Albania',
              'Algeria',
              'Andorra',
              'Angola',
              'Antigua and Barbuda',
              'Argentina',
              'Armenia',
              'Azerbaijan',
              'Bahamas',
              'Bahrain',
              'Bangladesh',
              'Barbados',
              'Belize',
              'Benin',
              'Bhutan',
              'Bolivia',
              'Bosnia and Herzegovina',
              'Botswana',
              'Brazil',
              'Brunei Darussalam',
              'Burkina Faso',
              'Burundi',
              'Cape Verde',
              'Cambodia',
              'Cameroon',
              'Central African Republic',
              'Chad',
              'Chile',
              'China',
              'Colombia',
              'Comoros',
              'Congo',
              'Cook Islands',
              'Costa Rica',
              'Cuba',
              'Democratic Republic of Congo',
              'Djibouti',
              'Dominica',
              'Dominican Republic',
              'Ecuador',
              'Egypt',
              'El Salvador',
              'Equatorial Guinea',
              'Eritrea',
              'Eswatini',
              'Ethiopia',
              'Fiji',
              'Gabon',
              'Gambia',
              'Georgia',
              'Ghana',
              'Grenada',
              'Guatemala',
              'Guinea',
              'Guinea-Bissau',
              'Guyana',
              'Haiti',
              'Holy See',
              'Honduras',
              'HongKong',
              'India',
              'Indonesia',
              'Iran',
              'Iraq',
              'Israel',
              'Ivory Coast',
              'Jamaica',
              'Jordan',
              'Kazakhstan',
              'Kenya',
              'Kiribati',
              'Kuwait',
              'Kyrgyzstan',
              'Laos',
              'Lebanon',
              'Lesotho',
              'Liberia',
              'Libya',
              'Madagascar',
              'Malawi',
              'Malaysia',
              'Maldives',
              'Mali',
              'Marshall Islands',
              'Mauritania',
              'Mauritius',
              'Mexico',
              'Micronesia',
              'Moldova',
              'Mongolia',
              'Montenegro',
              'Morocco',
              'Mozambique',
              'Myanmar',
              'Namibia',
              'Nauru',
              'Nepal',
              'Nicaragua',
              'Niger',
              'Nigeria',
              'Niue',
              'North Macedonia',
              'North Korea',
              'Oman',
              'Pakistan',
              'Palau',
              'Panama',
              'Papua New Guinea',
              'Paraguay',
              'Peru',
              'Philippines',
              'Qatar',
              'Rwanda',
              'Saint Kitts and Nevis',
              'Saint Lucia',
              'Saint Vincent and the Grenadines',
              'Samoa',
              'San Marino',
              'Sao Tome and Principe',
              'Saudi Arabia',
              'Senegal',
              'Serbia',
              'Seychelles',
              'Sierra Leone',
              'Singapore',
              'Solomon Islands',
              'Somalia',
              'South Africa',
              'South Korea',
              'South Sudan',
              'Sri Lanka',
              'Palestine',
              'Sudan',
              'Suriname',
              'Syria',
              'Taiwan',
              'Tajikistan',
              'Tanzania',
              'Thailand',
              'Timor-Leste',
              'Togo',
              'Tonga',
              'Trinidad and Tobago',
              'Tunisia',
              'Turkmenistan',
              'Tuvalu',
              'Uganda',
              'United Arab Emirates',
              'Uruguay',
              'Uzbekistan',
              'Vanuatu',
              'Venezuela',
              'Vietnam',
              'Yemen',
              'Zambia',
              'Zimbabwe']

ldc = ['Afghanistan',
       'Angola',
       'Bangladesh',
       'Benin',
       'Bhutan',
       'Burkina Faso',
       'Burundi',
       'Cambodia',
       'Central African Republic',
       'Chad',
       'Comoros',
       'Democratic Republic of Congo',
       'Djibouti',
       'Eritrea',
       'Ethiopia',
       'Gambia',
       'Guinea',
       'Guinea-Bissau',
       'Haiti',
       'Kiribati',
       'Laos',
       'Lesotho',
       'Liberia',
       'Madagascar',
       'Malawi',
       'Mali',
       'Mauritania',
       'Mozambique',
       'Myanmar',
       'Nepal',
       'Niger',
       'Rwanda',
       'Sao Tome and Principe',
       'Senegal',
       'Sierra Leone',
       'Solomon Islands',
       'Somalia',
       'South Sudan',
       'Sudan',
       'Timor-Leste',
       'Togo',
       'Tuvalu',
       'Uganda',
       'Tanzania',
       'Yemen',
       'Zambia']

annex1_regions = ['East Asia',
                  'Europe',
                  'America',
                  'Asia',
                  'North America',
                  'East Europe',
                  'North Europe',
                  'West Europe',
                  'South Europe',
                  'Central Europe']

non_annex1_regions = ['Asia',
                      'East Asia',
                      'North Asia',
                      'West Asia',
                      'South Asia',
                      'Southeast Asia',
                      'Central Asia',
                      'America',
                      'South America',
                      'Central America',
                      'Latin America',
                      'Africa',
                      'East Africa',
                      'North Africa',
                      'West Africa',
                      'Southern Africa',
                      'Central Africa',
                      'Sub-Saharan Africa',
                      'Sahel',
                      'Sahelian Africa',
                      'Pacific Islands',
                      'Carribean',
                      'Small Island Developing States',
                      'Korea',
                      'South Europe',
                      'Europe',
                      'North America']

ldc_regions = ['Asia',
               'South Asia',
               'Southeast Asia',
               'Sahelian Africa',
               'Sub-Saharan Africa',
               'West Africa',
               'Central Africa',
               'East Africa',
               'North Africa',
               'Africa']

research_regions = ['Annex1', 'NonAnnex1', 'LDC', 'USA', 'China', 'India']

split_regions_list = ['central and south america',
                      'north and south america',
                      'central and south china',
                      'central and east africa',
                      'central and northern europe',
                      'central and southern asia',
                      'northern and eastern europe']

region_check_list = list(set(annex1 + non_annex1 + ldc + non_annex1_regions + annex1_regions + ldc_regions + ['Global']))
region_check_list_lower = [region.lower() for region in region_check_list]

country_check_list = list(set(annex1 + non_annex1 + ldc))
country_check_list_lower = [country.lower() for country in country_check_list]

exclude_regions = non_annex1_regions + annex1_regions + ldc_regions
exclude_regions = [r.lower() for r in exclude_regions]